{{- if .Values.retentionPolicy.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: camunda-platform-curator
  labels:
    {{- include "camundaPlatform.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.retentionPolicy.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: "{{ .Values.retentionPolicy.image.repository }}:{{ .Values.retentionPolicy.image.tag }}"
              name: curator
              args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
              volumeMounts:
                - name: config
                  mountPath: /etc/config
          volumes:
            - name: config
              configMap:
                name: camunda-platform-curator-config
                defaultMode: 0744
          restartPolicy: OnFailure
{{- end }}
