global:
  zeebe: "{{ .Release.Name }}-zeebe"
  elasticsearch:
    host: "opensearch-cluster-master"
    port: 9200
    clusterName: "opensearch"

logging:
  level:
    ROOT: INFO
    org.camunda.tasklist: DEBUG

service:
  type: ClusterIP
  port: 80
image:
  repository: camunda/tasklist
  tag: 1.2.8

resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"    
  path: /
  host:
