style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/camunda/camunda-platform-helm
options:
  commits:
    filters:
      Type:
        - build
        - ci
        - docs
        - feat
        - fix
        - refactor
        - style
        - test
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
