apiVersion: v2
description: Zeebe Helm Chart for Kubernetes
name: zeebe
type: application
version: 8.1.1
icon: https://helm.camunda.io/imgs/camunda.svg
annotations:
  artifacthub.io/changes: |
    - rewrite zeebe chart
  artifacthub.io/containsSecurityUpdates: "false"
