name: "Chart - Release"

on:
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger release manually'
        required: false
        default: false
        type: boolean

  pull_request:
    types:
      - labeled

jobs:
  wait-for-release-conditions:
    if: ${{ contains(github.event.*.labels.*.name, 'release') || github.event.inputs.trigger }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for all PR checks to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'wait-for-release-conditions'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  release:
    needs: wait-for-release-conditions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: asdf-vm/actions/install@v1
      - name: Add Helm repos
        run: |
          make helm.repos-add
      - name: Update Helm dependency
        run: |
          make helm.dependency-update
      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          config: .github/config/chart-releaser.yaml
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: 'true'
