name: Go CI

on:
  push:
    branches: [ main ]
  pull_request: { }

env:
  HELM_VERSION: 3.6.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Format
      run: |
        make fmt
        diff=$(git status --porcelain)
        if [ -n "$diff" ]
        then
          echo "Some files are not following the go format ($diff), run gofmt and fix your files."
          exit 1
        fi
    - name: Install License Tool
      run: make installLicense
    - name: Check License
      run: make checkLicense
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: "${{ env.HELM_VERSION }}"
    - name: Add helm repos
      run: |
        helm repo add elastic https://helm.elastic.co
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
    - name: Get Helm Deps
      run: make deps
    - name: Test
      run: make test
