name: Helm Lint Charts

on:
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: { }
env:
  HELM_VERSION: 3.6.3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"
      - name: Add necessary helm repos
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
      - name: Get Helm Deps
        run: |
          make deps
      - name: Run Helm lint 
        run: |
          helm lint --strict charts/*
