name: "Test - Unit"

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

jobs:
  test:
    name: Custom values
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Format
      run: make go.fmt
    - name: Install License Tool
      run: make go.addlicense-install
    - name: Check License
      run: make go.addlicense-check
    - name: Install Helm
      uses: asdf-vm/actions/install@v1
    - name: Add helm repos
      run: make helm.repos-add
    - name: Get Helm dependency
      run: make helm.dependency-update
    - name: Test
      run: make go.test
